# Generated by Django 4.0.6 on 2022-07-14 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('active', 'Active'), ('deactivated', 'Deactivated')], default='', max_length=20),
        ),
    ]
