# Generated by Django 4.0.6 on 2022-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_owner_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(max_length=800, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('active', 'Active'), ('deactivated', 'Deactivated')], default='in_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
